version: '3.7'

services:
    db:
        restart: always
        image: postgres:latest
        volumes:
            - pgdata:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: django
            POSTGRES_PASSWORD: django
    api:
        build: ./store
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./store:/django
        ports:
            - "8000:8000"
        links:
            - db

        depends_on:
            - db
        environment:
            DEBUG: "true"
            DATABASE_NAME: django
            DATABASE_USER: django
            DATABASE_PASSWORD: django
            DATABASE_SERVICE_HOST: database
volumes:
    pgdata:
    static_volume: